### ISSUE TITLE
An Alternative .ToString()

### ISSUE THREAD

**Issue by uncheckederror** [MrSoxAndShoes/Entities#1]
https://github.com/MrSoxAndShoes/Entities/blob/426d175038e3792afba15323f3d5160e0f1f1245/entity.py#L238

In the current .ToString() implementation, a StringBuilder is created and then the Column Name and the value for that Column are added in pairs to the StringBuilder object. This is a pretty straight forward implementation, although it requires you to do a bit of string formatting to get it to look right.

As a "simpler" alternative it could be implemented this way:

```csharp
using System.Text.Json;

public override string ToString()
{
    return JsonSerializer.Serialize(this);
}
```
This method relies on the System.Text.Json library to serialize the DTO into a string, internally formatted as valid JSON, to represent the DTO. This library is available as part of the ASP.NET Core runtime starting in .NET Core 3.0 (September 2019), so no additional NuGet packages are required.

A benefit of this method is that you can run it in reverse by copying the output of .ToString() and using it as the input for a .FromJSON(string json) method:

```csharp
using System.Text.Json;

public static DTO? FromJSON(string json)
{
    return JsonSerializer.Deserialize<DTO>(json);
}
```

Which can be quite helpful when creating an instance of the DTO with known values to use for automated testing. Additionally, you don't have to do any of the string formatting yourself and the string representation of the DTO is in JSON which is a well-known and familiar format.

I like this project as I often find myself manually creating DTOs to represent existing tables/views/stored procedures in SQL Server. EF Core does support [automatically scaffolding](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/?tabs=dotnet-core-cli) an existing SQL Server database. Although I have had mixed success with it, as it's awkward and temperamental to figure out the correct commands to pass it, especially if your project has multiple database contexts.

**Comment by MrSoxAndShoes** [comment]
It depends on the intended usage. For DTOs, I have an object extension ToJson() and call it from the overridden ToString() method to output the instance as JSON. For my entities though, I don't typically output them to the user and instead override ToString() to display summaries during debugging like this:

```cs
var sb = new StringBuilder();

sb.AppendLine($"Account Number: {ACCOUNT_NUMBER} ({ACCOUNT_ID_NUMBER})");
sb.AppendLine($"  Site Address: {SITE_ADDRESS_LINE_1}");
sb.AppendLine($"                {SITE_CITY_STATE_ZIP_CODE}");
sb.AppendLine($"  Contact Name: {CONTACT_NAME}");
sb.AppendLine($"                {ATTENTION_TO}");
sb.AppendLine($"  Mailing Address: {MAIL_ADDR_LINE_1}");
sb.AppendLine($"                   {MAIL_ADDR_LINE_2}");
sb.AppendLine($"                   {MAIL_CITY_STATE_ZIP_CODE}");
sb.AppendLine($"                   {MAIL_COUNTRY_NAME}");
sb.AppendLine($"  PLSS Section: {PLSS_SECTION}");
sb.AppendLine($"  Account Type: {ACCOUNT_TYPE}");
sb.AppendLine($"  Account Status: {ACCOUNT_STATUS} ({ACCOUNT_STATUS_DATE:d})");
sb.AppendLine($"  Real Account ID: {PROP_REAL_ACCOUNT_ID}");

return sb.ToString();
```

IOW, the intent for the ToString() override in the entities is to provide a head start on the output with all the class properties and let the developer edit to their liking.
